### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by Doomlol** [jucasoliveira/terminalGPT#34]
> terminalgpt@1.0.7 chat
> node bin/index.js chat --engine text-davinci-002 --temperature 0.7

/home/meet/Projects/terminalGPT/bin/utils.js:36
    if (request == undefined || !request.data?.choices?.[0].text) {
                                              ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/meet/Projects/terminalGPT/bin/index.js:9:44)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by jucasoliveira** [comment]
@Doomlol thanks for finding this issue. Can you provide which input you added on the chat ?
